# Week 2 Guided Lab: First Data Profile with Python and Pandas
**BAN 6003 Data Management and Analytics Integration**

This guided lab supports the Week 2 module: **Why Data Management Matters**.

Last week, we asked: **Where does data live?**  
This week, we ask: **What is the condition of our data?**

In this lab, we are **not cleaning the data yet**. We are acting as data detectives. Our goal is to inspect the structure, content, and quality of a dataset before making cleaning or modeling decisions.

## Lab Learning Goals
By the end of this guided lab, you should be able to:

1. Run basic Python code in a notebook.
2. Explain why Pandas is useful for tabular data.
3. Load a CSV file using `pd.read_csv()`.
4. Inspect a DataFrame using `head()`, `tail()`, `shape`, `columns`, `info()`, and `dtypes`.
5. Profile missing values using `isna().sum()`.
6. Generate numerical summaries using `describe()` and selected summary methods.
7. Generate categorical summaries using `value_counts()`.
8. Identify possible duplicate IDs.
9. Write short observations about the condition of a dataset.

---
# Part 1: Python Basics You Need for This Course

This course is not a full Python programming course. You do not need to memorize every Python feature right now.

For this course, the most important early skills are:
- running code cells;
- reading code carefully;
- changing small pieces of example code;
- interpreting the output;
- writing short notes about what you observe.

## 1.1 Python as a Calculator
Python can perform calculations directly. Try running the cell below.

In [1]:
# If you run a 10 kilometer race in 43 minutes and 30 seconds,
# what is your average seconds per mile?
# 1 mile = 1.61 kilometers

seconds = 43 * 60 + 30
miles = 10 / 1.61
seconds_per_mile = seconds / miles

seconds_per_mile

420.21000000000004

## 1.2 Storing Objects as Variables
We use the `=` sign to store values in variables.

Variable names are case-sensitive. For example, `salary`, `Salary`, and `SALARY` are different names.

In [4]:
name = "Alice"
# Karrar learn about the "  "
age = 28
salary = 95000.0
is_manager = False

print(name)
print(age)
print(salary)
print(is_manager)

print(type(name), type(age), type(salary), type(is_manager))

Alice
28
95000.0
False
<class 'str'> <class 'int'> <class 'float'> <class 'bool'>

## 1.3 Comments
Anything after `#` is a comment. Python ignores comments, but humans use them to explain code.

You should get ready to comment your code often in this course.

In [5]:
# This is a comment. It explains what the code does.

message1 = "It's not a bug; it's a feature."
print(message1)

It's not a bug; it's a feature.

## 1.4 Lists
A list stores multiple values in order. Python uses zero-based indexing, so the first element is at position `0`.

In [6]:
departments = ["Engineering", "Marketing", "Sales"]
# karrar lean about how to do list.
print(departments)
print(departments[0])  # first element
print(departments[1])  # second element

['Engineering', 'Marketing', 'Sales']
Engineering
Marketing

Lists can be changed. For example, we can replace the first element.

In [7]:
vector1 = [1, 2, 3]
vector1[0] = 100
print(vector1)

[100, 2, 3]

A common beginner surprise: multiplying a Python list by 2 repeats the list. It does **not** multiply each element.

In [8]:
vector1 = [100, 2, 3]
print(vector1 * 2)

[100, 2, 3, 100, 2, 3]

If we really want to multiply each element, one option is a loop. Another option is a list comprehension. This is useful to see, but you do not need to master it today.

In [9]:
# Loop version
new_vector = []
for x in vector1:
    new_vector.append(x * 2)
print(new_vector)

# Optional: list comprehension version
[x * 2 for x in vector1]

[200, 4, 6]

[200, 4, 6]

## 1.5 Dictionaries
A dictionary stores values using key-value pairs. Dictionaries are useful because many datasets also use names or labels to access values.

In [11]:
employee = {
    "name": "Bob",
    "department": "Marketing",
    "salary": 78000
}

print(employee["name"])
print(employee["department"])
print(employee["salary"])
# karrar learn about how [ ] works

Bob
Marketing
78000

## 1.6 A Quick Note on Errors and Debugging
Programming is error-prone. Errors are normal.

Common error types include:
- **Syntax errors:** Python cannot understand the code structure.
- **Runtime errors:** the code starts running but fails during execution.
- **Semantic errors:** the code runs, but the result is not what you intended.

Good debugging habits:
- Read the error message.
- Check the line where the error happened.
- Run code one cell at a time.
- Use `help()` when needed.
- Ask a clear question with the exact error message.

In [12]:
help(print)

Help on built-in function print in module builtins:

print(*args, sep=' ', end='\n', file=None, flush=False)
    Prints the values to a stream, or to sys.stdout by default.

    sep
      string inserted between values, default a space.
    end
      string appended after the last value, default a newline.
    file
      a file-like object (stream); defaults to the current sys.stdout.
    flush
      whether to forcibly flush the stream.

---
# Part 2: What is Pandas?

Pandas is one of the most important Python tools for data analysts and data scientists. It helps us work with tabular data: rows and columns.

Pandas is useful because it can:
- load data from CSV, Excel, databases, and other sources;
- store data in DataFrames;
- inspect, filter, summarize, group, clean, and transform data;
- connect later to modeling tools such as Scikit-learn.

## 2.1 Import Pandas
By convention, we import Pandas using the shorter name `pd`.

In [13]:
import pandas as pd
print("Pandas imported successfully!")
# karrar pandas for panal data , by clicking on run , you will run the pandas function

Pandas imported successfully!

## 2.2 Series and DataFrame
The two main Pandas objects are:

- **Series:** one column of data.
- **DataFrame:** a table made of multiple Series.

Most of the time in this course, we will work with DataFrames.

In [14]:
sample = pd.DataFrame({
    "employee_id": [1, 2, 3],
    "department": ["Sales", "Marketing", "Engineering"],
    "salary": [60000, 75000, 90000]
})

sample

   employee_id   department  salary
0            1        Sales   60000
1            2    Marketing   75000
2            3  Engineering   90000

A single column from a DataFrame is a Series.

In [ ]:
sample["department"]
# karrar this like using print

0          Sales
1      Marketing
2    Engineering
Name: department, dtype: str

## 2.3 Methods vs Attributes
In Pandas, you will see both methods and attributes.

- A **method** uses parentheses because it performs an action: `df.head()`.
- An **attribute** does not use parentheses because it stores information: `df.shape`.

This distinction matters because `df.shape` and `df.shape()` are not the same.

In [17]:
print("DataFrame shape attribute:")
print(sample.shape)

print("DataFrame head method:")
sample.head()

DataFrame shape attribute:
(3, 3)
DataFrame head method:

   employee_id   department  salary
0            1        Sales   60000
1            2    Marketing   75000
2            3  Engineering   90000

---
# Part 3: Data Import

Our most common first step is loading a CSV file into a Pandas DataFrame.

## 3.1 CSV Files: Basic Python vs Pandas
Python has a built-in `csv` module, but it gives us rows as lists. Pandas gives us a DataFrame, which is much easier for profiling and analysis.

You do not need to use the built-in `csv` module in this course, but the example below shows why Pandas is convenient.

In [18]:
import csv

csv_rows = []
with open("../data/employee_data.csv", "r") as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        csv_rows.append(row)

# Show only the first 3 rows so the output is not too long
csv_rows[:3]

[['\ufeffemployee_id',
  'first_name',
  'last_name',
  'hire_date',
  'department',
  'salary',
  'age',
  'full_time'],
 ['101', 'John', 'Smith', '4/15/22', 'Marketing', '85000', '34', 'TRUE'],
 ['102', 'Jane', 'Doe', '8/20/21', 'Sales', '92000', '45', 'TRUE']]

In [19]:
df = pd.read_csv("../data/employee_data.csv")
df.head()

,employee_id,first_name,last_name,hire_date,department,salary,age,full_time
0,101,John,Smith,4/15/22,Marketing,85000,34.0,True
1,102,Jane,Doe,8/20/21,Sales,92000,45.0,True
2,103,Peter,Jones,1/2/22,HR,71000,29.0,True
3,104,Mary,Johnson,11/10/23,Engineering,115000,38.0,True
4,105,Mike,Brown,5/30/20,sales,89000,NaN,False

## 3.2 Load the Employee Dataset
For this lab, we will use `employee_data.csv` in the `data` folder.

The command below reads the CSV file and stores it as a DataFrame named `df`.

In [20]:
df = pd.read_csv("../data/employee_data.csv")
print("Data loaded successfully!")

Data loaded successfully!

---
# Part 4: First Look at the Data

Before cleaning or modeling, we need to understand the dataset's structure.

## 4.1 First Rows
`head()` shows the first five rows by default. This helps us quickly see column names and example values.

In [ ]:
df.head()

## 4.2 Last Rows
`tail()` shows the last five rows by default.

In [ ]:
df.tail()

## 4.3 Dataset Size
`shape` tells us the number of rows and columns.

In [ ]:
df.shape

Let's store the row and column counts in separate variables and print a readable message.

In [ ]:
num_rows, num_columns = df.shape
print(f"This dataset has {num_rows} rows and {num_columns} columns.")

## 4.4 Column Names
`columns` shows all column names.

In [ ]:
df.columns

## 4.5 Data Types and Non-Missing Counts
`info()` is one of the most useful profiling tools. It shows:
- column names;
- non-missing counts;
- data types.

In [ ]:
df.info()

## 4.6 Data Types Only
`dtypes` gives a shorter view of the data type for each column.

In [ ]:
df.dtypes

---
# Part 5: Data Profiling Checklist

When we profile data, we ask questions like:

1. How many rows and columns are there?
2. What are the data types?
3. Are there missing values?
4. What are the minimum, maximum, average, and typical values for numerical columns?
5. Are categorical values consistent?
6. Are there duplicate IDs or duplicate rows?

We are still diagnosing the data. We are not fixing it yet.

## 5.1 Missing Values
Missing values are often shown as `NaN` in Pandas. They may come from blank cells, system errors, unavailable information, or values that were never collected.

In [ ]:
df.isna().sum()

It is often helpful to turn missing counts into percentages.

In [ ]:
missing_summary = pd.DataFrame({
    "missing_count": df.isna().sum(),
    "missing_percent": df.isna().mean() * 100
})

missing_summary

## 5.2 Numerical Summary with `describe()`
`describe()` provides a quick summary of numerical columns.

It includes:
- count of non-missing values;
- mean;
- standard deviation;
- minimum;
- 25th, 50th, and 75th percentiles;
- maximum.

In [ ]:
df.describe()

## 5.3 Individual Numerical Summary Methods
Sometimes we want one statistic for one column.

The exact column names in your dataset matter. If a column name below does not exist, check `df.columns` and adjust the code.

In [ ]:
# Example: summary statistics for age
print("Count:", df["age"].count())
print("Mean:", df["age"].mean())
print("Median:", df["age"].median())
print("Minimum:", df["age"].min())
print("Maximum:", df["age"].max())
print("Standard deviation:", df["age"].std())

## 5.4 Categorical Summary with `value_counts()`
For categorical variables, use `value_counts()` to see how often each value appears.

In [ ]:
df["department"].value_counts()

We can also include missing values in the count by using `dropna=False`.

In [ ]:
df["department"].value_counts(dropna=False)

## 5.5 Unique Values
`nunique()` counts the number of unique values in a column.

In [ ]:
df["department"].nunique()

## 5.6 Duplicate Records and Duplicate IDs
A full duplicate row means every value in the row is repeated. A duplicate ID means a column that should uniquely identify records appears more than once.

Both can be important, but they are not always the same issue.

In [ ]:
# Count fully duplicated rows
full_duplicate_rows = df.duplicated().sum()
print(f"Number of fully duplicated rows: {full_duplicate_rows}")

In [ ]:
# Count duplicate employee IDs
employee_id_duplicates = df["employee_id"].duplicated().sum()
print(f"Number of duplicated employee_id values after the first occurrence: {employee_id_duplicates}")

`value_counts()` can help us see which IDs appear more than once.

In [ ]:
df["employee_id"].value_counts().head(10)

---
# Part 6: Writing Data Quality Observations

Profiling is not just running code. You also need to communicate what you found.

A good data quality observation is specific and evidence-based.

## Examples of Good Observations
- The dataset has 500 rows and 8 columns.
- The `salary` column appears to have missing values.
- The `department` column has several categories, and I would check whether category labels are consistent.
- Some `employee_id` values appear more than once, which may be a duplicate-record issue.
- The maximum value of `age` seems unusually high and should be investigated.

Now write your own observations below.

## Your Turn: Write 3–5 Observations
Replace the prompts below with your own observations.

1. [Observation 1]
2. [Observation 2]
3. [Observation 3]
4. [Optional Observation 4]
5. [Optional Observation 5]

---
# Part 7: Optional Challenge

These tasks are optional. They are for students who already feel comfortable and want to explore more.

In [ ]:
# Optional challenge 1: Choose another categorical column and run value_counts().
# Replace "department" with another column name if appropriate.

df["department"].value_counts(dropna=False)

In [ ]:
# Optional challenge 2: Show rows with at least one missing value.

df[df.isna().any(axis=1)].head()

In [ ]:
# Optional challenge 3: Sort by a numerical column.
# If salary is stored as text in this dataset, this may not sort the way you expect.
# That is okay! We will learn how to fix data types in Week 3.

df.sort_values("salary", ascending=False).head()

---
# Part 8: What Comes Next?

In Week 2, we profile the data. We ask: **What is the condition of the data?**

In Week 3, we begin cleaning. We ask: **How do we carefully fix the problems we found?**

Week 3 will cover:
- correcting data types;
- handling duplicates;
- handling missing values;
- documenting cleaning decisions.

## Save Your Work
If this notebook is part of your assignment repository, save the notebook and push your changes when instructed.

```bash
git add .
git commit -m "Completed Week 2 guided lab"
git push
```